# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{autotest-screen}
  s.version = "0.1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David J. Hamilton"]
  s.date = %q{2010-07-15}
  s.description = %q{
      Update Gnu Screen caption with autotest results.

      Specifically, when autotest is running with an ancestor [Gnu] screen
      process, have that screen's caption set when autotest runs tests.

      Conceptually similar to autotest-growl but with a different notification system.
    }
  s.email = %q{autotest-screen@hjdivad.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     ".gvimrc",
     ".rspec",
     ".rvmrc",
     ".vim/ftplugin/.gitignore",
     ".vim/plugin/.gitignore",
     ".vimproject",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "autotest-screen.gemspec",
     "autotest/discover.rb",
     "lib/autotest-screen.rb",
     "lib/autotest/result.rb",
     "lib/autotest/screen.rb",
     "spec/autotest-screen_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/hjdivad/autotest-screen}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Update Gnu Screen caption with autotest results.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/autotest-screen_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta.17"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta.17"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta.17"])
  end
end

